### ISSUE TITLE
AppManager panic 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by weiqiushi** [buckyos/CYFS#231]
found an app manager panic, panic info: 
> CYFS service panic report: 
product:cyfs-service
service:app-manager
bin:app-manager
channel:beta
target:x86_64-unknown-linux-gnu
version:1.1.1.82-beta (23-04-15)
msg:{
  "msg": "thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: \"err: (Unknown, http-tcp request to 127.0.0.1:1318 failed! during=7ms, Connection reset by peer (os error 104), None)\"': service/app-manager/src/non_helper.rs:441
0: 0x000055f191cab470
1: 0x000055f191ca0400
2: 0x000055f191c43c70
3: 0x000055f19212cb10
4: 0x000055f19212ca30
5: 0x000055f19212b180
6: 0x000055f19212c7a0
7: 0x000055f191358670
8: 0x000055f1913588e0
9: 0x000055f19149fac0
10: 0x000055f19149aae0
11: 0x000055f1914c7a00
12: 0x000055f1914ac0e0
13: 0x000055f1914af2c0
14: 0x000055f1914088b0
15: 0x000055f1914ab960
16: 0x000055f1914e93c0
17: 0x000055f192099490
18: 0x000055f192099590
19: 0x000055f1920a26f0
20: 0x000055f19209e230
21: 0x000055f1920a1c30
22: 0x000055f1920979f0
23: 0x000055f19209f090
24: 0x000055f192132ed0
25: 0x00007f618635f850
26: 0x00007f61863f0bae
27: 0x0000000000000000",
  "msg_with_symbol": "thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: \"err: (Unknown, http-tcp request to 127.0.0.1:1318 failed! during=7ms, Connection reset by peer (os error 104), None)\"': service/app-manager/src/non_helper.rs:441
   0: cyfs_debug::panic::manager::PanicManager::start::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: std::thread::local::LocalKey<T>::with
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: async_task::raw::RawTask<F,T,S>::run
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  17: async_io::driver::block_on
  18: async_global_executor::reactor::block_on
  19: async_global_executor::threading::thread_main_loop
  20: std::sys_common::backtrace::__rust_begin_short_backtrace
  21: core::ops::function::FnOnce::call_once{{vtable.shim}}
  22: std::sys::unix::thread::Thread::new::thread_start
  23: <unknown>
  24: __clone
",
  "hash": "972b331b810574bee8746693ce7dd0e9"
}

**Comment by weiqiushi** [comment]
Fixed. This is probably caused by the gateway exiting while the app-manager is running.
https://github.com/buckyos/CYFS/blob/7ead2f7b3aa6a658dcf30c7a930b70e00b853906/src/service/app-manager/src/non_helper.rs#L435-L446
I don't know why the previous developer used unwrap() here and used the question mark expression elsewhere .....
