### ISSUE TITLE
cyfs create -n project_name error

### ISSUE THREAD

**Issue by justtwo2** [buckyos/CYFS#61]
```
E:\lzh_space\WebFree\src>cyfs create -n free
[info],[2022-10-25 22:15:14.275],<>,cyfs-sdk version 1.0-beta (2022-10-13), index.js:45039
[info],[2022-10-25 22:15:18.924],<>,[cyfs], Tool Dir： C:\Users\11025\AppData\Roaming\npm\node_modules\cyfs-tool, cyfs.js:3213
[info],[2022-10-25 22:15:18.924],<>,[cyfs], Version： 0.5.13, cyfs.js:3214
[info],[2022-10-25 22:15:18.930],<>,use owner at C:\Users\11025\.cyfs_profile\people, cyfs.js:133
[info],[2022-10-25 22:15:18.931],<>,will check cyfs_config_dir:  E:\lzh_space\WebFree\src\free\.cyfs, cyfs.js:3303
[warn],[2022-10-25 22:15:19.210],<>,read unknown body ext content! len=4661, obj_type=2, index.js:50466
C:\Users\11025\AppData\Roaming\npm\node_modules\cyfs-tool\node_modules\cyfs-sdk\index.js:20895
    return new Uint8Array(this.buffer, this.byteOffset + size);
           ^

RangeError: Start offset 4889 is outside the bounds of the buffer
    at new Uint8Array (<anonymous>)
    at Uint8Array.offset (C:\Users\11025\AppData\Roaming\npm\node_modules\cyfs-tool\node_modules\cyfs-sdk\index.js:20895:12)
    at ObjectMutBodyDecoder.raw_decode (C:\Users\11025\AppData\Roaming\npm\node_modules\cyfs-tool\node_modules\cyfs-sdk\index.js:50468:23)
    at PeopleDecoder.raw_decode (C:\Users\11025\AppData\Roaming\npm\node_modules\cyfs-tool\node_modules\cyfs-sdk\index.js:52323:43)
    at StandardObjectDecoder.raw_decode (C:\Users\11025\AppData\Roaming\npm\node_modules\cyfs-tool\node_modules\cyfs-sdk\index.js:47498:56)
    at Object.load_desc_and_sec (C:\Users\11025\AppData\Roaming\npm\node_modules\cyfs-tool\cyfs.js:3535:52)
    at setup_app_obj (C:\Users\11025\AppData\Roaming\npm\node_modules\cyfs-tool\cyfs.js:73:39)
    at run (C:\Users\11025\AppData\Roaming\npm\node_modules\cyfs-tool\cyfs.js:150:5)
    at Command.<anonymous> (C:\Users\11025\AppData\Roaming\npm\node_modules\cyfs-tool\cyfs.js:138:9)
    at Command.listener [as _actionHandler] (C:\Users\11025\AppData\Roaming\npm\node_modules\cyfs-tool\node_modules\commander\lib\command.js:488:17)
```

**Comment by justtwo2** [comment]
run this command frist is error ,run this command second is success.

**Comment by weiqiushi** [comment]
Closed by no any futher infomation. it seems you have provided a wrong/or very old people desc and sec files. Reopen it when this error appears again
